# Generated by Django 4.1.7 on 2023-03-16 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_functional.cities')),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('house', models.PositiveSmallIntegerField()),
                ('opening_time', models.PositiveSmallIntegerField(default=9)),
                ('closing_time', models.PositiveSmallIntegerField(default=21)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_functional.cities')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_functional.streets')),
            ],
        ),
    ]
